# Generated by Django 4.0.1 on 2022-01-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trailer_link',
            field=models.CharField(default='no link', max_length=255),
        ),
    ]
